import cv2 as cv
import numpy as np

import sys

def wavelet(t, tau=0, s=1):
    '''
    Represents a daughter wavelet generated by the mother wavelet.
    '''
    def mother_wavelet(t):
        '''
        Represents the mother wavelet.
        '''
        return np.exp(-t*t / 2) - 0.5*np.exp(-t*t / 8)

    return 1/np.sqrt(s) * mother_wavelet(t-tau / s)

def wavelet_transform(image):
    '''
    Performs the wavelet transform of an `image`.
    '''
    pass

def main():
    '''
    The main function of the program.
    '''
    path = input('path: ')

    image = cv.imread(path, cv.IMREAD_UNCHANGED)

    cv.imshow('Initial Image', image)

    # Waiting for user.
    cv.waitKey(0)

    sys.exit(0)

if __name__ == '__main__':
    main()
