import cv2 as cv
import numpy as np

import os
import sys

def mother_wavelet(t):
    '''
    Represents the mother wavelet with `t` parameter.
    '''
    return np.exp(-t*t / 2) - 0.5*np.exp(-t*t / 8)

def wavelet(t, tau, s):
    '''
    Represents a daughter wavelet generated by the mother wavelet with `t`,
    `tau` and `s` parameters.
    '''
    return 1/np.sqrt(s) * mother_wavelet(t-tau / s)

def wavelet_transform(image):
    '''
    Performs the wavelet transform of an `image`.
    '''
    pass

def main():
    '''
    The main function of the program.
    '''
    path = input('path: ')

    if not os.path.exists(path):
        print(f'error: \'{path}\' does not exists', file=sys.stderr)
        sys.exit(1)

    image = cv.imread(path, cv.IMREAD_UNCHANGED)

    cv.imshow('Initial Image', image)

    # Wait for user.
    cv.waitKey(0)

    sys.exit(0)

if __name__ == '__main__':
    main()
